"""Initial database schema

Revision ID: df8b9b25ed7f
Revises: 
Create Date: 2025-11-18 10:25:41.881960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8b9b25ed7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learned_constraints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint_path', sa.String(length=500), nullable=False),
    sa.Column('endpoint_method', sa.String(length=10), nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('constraint_type', sa.String(length=50), nullable=False),
    sa.Column('constraint_value', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_details_json', sa.JSON(), nullable=True),
    sa.Column('first_observed', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_observed', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learned_constraints', schema=None) as batch_op:
        batch_op.create_index('idx_learned_confidence', ['confidence'], unique=False)
        batch_op.create_index('idx_learned_endpoint', ['endpoint_path', 'endpoint_method'], unique=False)
        batch_op.create_index('idx_learned_param', ['parameter_name'], unique=False)

    op.create_table('parsed_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('document_name', sa.String(length=500), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('document_path', sa.String(length=1000), nullable=True),
    sa.Column('parsed_content_json', sa.JSON(), nullable=False),
    sa.Column('endpoints_count', sa.Integer(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('parse_duration_ms', sa.Float(), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parsed_documents', schema=None) as batch_op:
        batch_op.create_index('idx_document_accessed', ['last_accessed'], unique=False)
        batch_op.create_index('idx_document_hash', ['document_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_parsed_documents_document_hash'), ['document_hash'], unique=True)

    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_tests', sa.Integer(), nullable=True),
    sa.Column('passed_tests', sa.Integer(), nullable=True),
    sa.Column('failed_tests', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_session_created', ['created_at'], unique=False)
        batch_op.create_index('idx_session_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_sessions_session_id'), ['session_id'], unique=True)

    op.create_table('coverage_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_coverage', sa.Float(), nullable=True),
    sa.Column('parameter_coverage', sa.Float(), nullable=True),
    sa.Column('status_code_coverage', sa.Float(), nullable=True),
    sa.Column('scenario_coverage', sa.Float(), nullable=True),
    sa.Column('overall_coverage', sa.Float(), nullable=True),
    sa.Column('total_endpoints', sa.Integer(), nullable=True),
    sa.Column('tested_endpoints', sa.Integer(), nullable=True),
    sa.Column('total_parameters', sa.Integer(), nullable=True),
    sa.Column('tested_parameters', sa.Integer(), nullable=True),
    sa.Column('total_status_codes', sa.Integer(), nullable=True),
    sa.Column('tested_status_codes', sa.Integer(), nullable=True),
    sa.Column('coverage_details_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_reports', schema=None) as batch_op:
        batch_op.create_index('idx_coverage_overall', ['overall_coverage'], unique=False)
        batch_op.create_index('idx_coverage_session', ['session_id'], unique=False)

    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('operation_id', sa.String(length=255), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('request_body_json', sa.JSON(), nullable=True),
    sa.Column('responses_json', sa.JSON(), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.create_index('idx_endpoint_path_method', ['path', 'method'], unique=False)
        batch_op.create_index('idx_endpoint_session', ['session_id'], unique=False)

    op.create_table('constraints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=255), nullable=False),
    sa.Column('parameter_type', sa.String(length=50), nullable=True),
    sa.Column('constraint_type', sa.String(length=50), nullable=True),
    sa.Column('constraint_value', sa.String(length=500), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.create_index('idx_constraint_endpoint', ['endpoint_id'], unique=False)
        batch_op.create_index('idx_constraint_param', ['parameter_name'], unique=False)

    op.create_table('test_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=True),
    sa.Column('test_name', sa.String(length=500), nullable=True),
    sa.Column('test_type', sa.String(length=50), nullable=True),
    sa.Column('scenario_type', sa.String(length=50), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_params_json', sa.JSON(), nullable=True),
    sa.Column('request_body_json', sa.JSON(), nullable=True),
    sa.Column('request_headers_json', sa.JSON(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body_json', sa.JSON(), nullable=True),
    sa.Column('response_headers_json', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('expected_status', sa.Integer(), nullable=True),
    sa.Column('actual_status', sa.Integer(), nullable=True),
    sa.Column('schema_valid', sa.Boolean(), nullable=True),
    sa.Column('schema_violations_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.create_index('idx_result_endpoint', ['endpoint_id'], unique=False)
        batch_op.create_index('idx_result_executed', ['executed_at'], unique=False)
        batch_op.create_index('idx_result_session', ['session_id'], unique=False)
        batch_op.create_index('idx_result_success', ['success'], unique=False)
        batch_op.create_index('idx_result_type', ['test_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_results', schema=None) as batch_op:
        batch_op.drop_index('idx_result_type')
        batch_op.drop_index('idx_result_success')
        batch_op.drop_index('idx_result_session')
        batch_op.drop_index('idx_result_executed')
        batch_op.drop_index('idx_result_endpoint')

    op.drop_table('test_results')
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.drop_index('idx_constraint_param')
        batch_op.drop_index('idx_constraint_endpoint')

    op.drop_table('constraints')
    with op.batch_alter_table('endpoints', schema=None) as batch_op:
        batch_op.drop_index('idx_endpoint_session')
        batch_op.drop_index('idx_endpoint_path_method')

    op.drop_table('endpoints')
    with op.batch_alter_table('coverage_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_coverage_session')
        batch_op.drop_index('idx_coverage_overall')

    op.drop_table('coverage_reports')
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_sessions_session_id'))
        batch_op.drop_index('idx_session_status')
        batch_op.drop_index('idx_session_created')

    op.drop_table('test_sessions')
    with op.batch_alter_table('parsed_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_documents_document_hash'))
        batch_op.drop_index('idx_document_hash')
        batch_op.drop_index('idx_document_accessed')

    op.drop_table('parsed_documents')
    with op.batch_alter_table('learned_constraints', schema=None) as batch_op:
        batch_op.drop_index('idx_learned_param')
        batch_op.drop_index('idx_learned_endpoint')
        batch_op.drop_index('idx_learned_confidence')

    op.drop_table('learned_constraints')
    # ### end Alembic commands ###
